### ISSUE TITLE
DockerFile error Step 6/16 : COPY conf/ /conf

### ISSUE THREAD

**Issue by ramielian** [openbridge/nginx#44]
hi,

It seems like there is an error in the docker file in the final steps, please see below.

Step 6/16 : COPY conf/ /conf
COPY failed: stat /var/lib/docker/tmp/docker-builder660373075/conf: no such file or directory

I tried to delete the lines:
COPY conf/ /conf
COPY test/ /tmp/test
 
but still failing to build. (Step 6/13 : COPY check_wwwdata.sh /usr/bin/check_wwwdata
COPY failed: stat /var/lib/docker/tmp/docker-builder849396188/check_wwwdata.sh: no such file or directory)

**Comment by tspicer** [comment]
It looks like you are missing assets in your build process. Because you do not have the assets the build is failing. 

Just look at this
```bash
COPY check_wwwdata.sh /usr/bin/check_wwwdata
COPY check_folder.sh /usr/bin/check_folder
```
If you do not have `check_wwwdata.sh` present on your host build dir, there is nothing to copy and hence an error.  So as far as I can tell, no, there is not an error in the Dockerfile. I just ran a complete build without issue. This has something to do with your local environment.
